server:
  port: 7777

spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          default-label: master
          uri: https://github.com/candradebh/microservices-repo/
          search-paths: mercado-financeiro, investimentos, fornecedor, loja, transportador, auth, myinvest