server:
  port: 7777

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: 'config-server'
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          default-label: master
          uri: https://github.com/candradebh/microservices-repo/
          search-paths: mercado-financeiro, investimentos, fornecedor, loja, transportador, auth, myinvest